<!DOCTYPE html>
<html lang="en">
    <?php echo $this->getPartial('head') ?>
    <body>
        <header class="page-header">
            <h1>The page you are looking for could not be found.</h1>
        </header>
        <section id="wrapper">
            <h5>Click <a href="<?php echo $this->getUrl() ?>">here</a> to get back to the home page</h5>
        </section>
        <footer>
            <?php echo $this->getPartial('footer') ?>
        </footer>
    </body>
</html>