<head>
    <title>MiniMVC PHP Framework</title>
    <meta name="keywords" content="" />
    <meta name="decription" content="" />
    <meta charset="utf-8">
    <link rel="icon" href="<?php echo $this->getUrl('images/favicon.ico') ?>" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo $this->getUrl('public/css/bootstrap.min.css') ?>" />
    <link rel="stylesheet" href="<?php echo $this->getUrl('public/css/bootstrap-theme.min.css') ?>"/>
    <link rel="stylesheet" href="<?php echo $this->getUrl('public/css/styles.css') ?>" />
    <script type="text/javascript" src="<?php echo $this->getUrl('public/js/jquery-1.12.2.min.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getUrl('public/js/bootstrap.min.js') ?>"></script>
</head>